FROM docker.io/library/archlinux@sha256:b944cc65c5f28665dfd5fdbf5ed2997c88f5bb4a0aefac7ee8a7ef01893e5ed9
COPY mirrorlist /etc/pacman.d/mirrorlist
RUN sed -i '/^\[options\]/a DisableDownloadTimeout' /etc/pacman.conf \
    && pacman -Syu --noconfirm --needed quickshell qt6-declarative qt6-svg qt6-wayland \
    hyprland weston dbus python jq curl git gum wayland-utils grim \
    ttf-jetbrains-mono-nerd mesa-utils xorg-server-xvfb \
    && mkdir -p /qa && pacman -Q > /qa/packages.txt \
    && useradd --create-home --uid 1000 omarchy
RUN pacman -S --noconfirm --needed sway && setcap -r /usr/bin/sway && pacman -Q > /qa/packages.txt
RUN pacman -S --noconfirm --needed inotify-tools wtype libpipewire && pacman -Q > /qa/packages.txt
RUN pacman -S --noconfirm --needed strace && pacman -Q > /qa/packages.txt
USER omarchy
WORKDIR /qa
ENV QT_QUICK_CONTROLS_STYLE=Basic
ENV LIBGL_ALWAYS_SOFTWARE=1
CMD ["bash"]
