hl.config({
  autogenerated = false,
  debug = { enable_stdout_logs = true, disable_logs = false },
  animations = { enabled = false },
  misc = { disable_hyprland_logo = true, disable_splash_rendering = true },
})
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
